log:
    debugLoggerPath: "log/"
    debugLoggerFile: "debug.log"

server:
    host: "0.0.0.0"
    port: 8080
    timezone: "Asia/Taipei"

db:
    dialect: "mysql"
    user: "root"
    password: "123456"
    host: "172.12.0.3"
    port: 3306
    database: "test1"
    flag: "charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci"
    interval: 60
    max_connections : 20

http:
    header:
        Access-Control-Allow-Origin: "*"
        Access-Control-Allow-Headers: "Content-Type, Authorization"
        Access-Control-Allow-Methods: "GET, POST, OPTIONS, HEAD, PATCH, DELETE"
